const fs = require("fs");
const path = require("path");

const repoRoot = path.resolve(__dirname, "..");
const examplesDir = path.join(repoRoot, "examples");
const goldenDir = path.join(repoRoot, "tests", "golden");
const htmlDemosDir = path.join(repoRoot, "docs", "demos", "html");
const outputDir = path.join(repoRoot, "docs", "site");

function main() {
  fs.mkdirSync(outputDir, { recursive: true });

  const examples = fs.readdirSync(examplesDir).filter(f => f.endsWith(".orgs"));

  const cards = examples.map(file => {
    const base = path.basename(file, ".orgs");
    const name = base.replace(/-/g, " ").replace(/\b\w/g, c => c.toUpperCase());
    
    return `
    <div class="card">
      <h3>${name}</h3>
      <div class="links">
        <a class="btn btn-html" href="./demos/${base}.html">Docs (HTML)</a>
        <a class="btn" href="./artifacts/${base}.summary.md">Summary (MD)</a>
        <a class="btn" href="./artifacts/${base}.mermaid.md">Diagram (Mermaid)</a>
        <a class="btn" href="./artifacts/${base}.formatted.orgs">Source (.orgs)</a>
      </div>
    </div>`;
  }).join("\n");

  const indexHtml = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>OrgScript Showcase</title>
  <style>
    body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; padding: 2rem; max-width: 1000px; margin: 0 auto; color: #1e293b; background: #f8fafc; line-height: 1.5; }
    h1 { border-bottom: 2px solid #e2e8f0; padding-bottom: 0.5rem; color: #0f172a; }
    h2 { color: #64748b; font-weight: 500; font-size: 1.25rem; }
    .grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(300px, 1fr)); gap: 1.5rem; margin-top: 2rem; }
    .card { background: white; padding: 1.5rem; border-radius: 12px; box-shadow: 0 4px 6px -1px rgba(0,0,0,0.1); border: 1px solid #e2e8f0; }
    .card h3 { margin-top: 0; margin-bottom: 1rem; color: #1e293b; }
    .links { display: flex; flex-wrap: wrap; gap: 0.5rem; }
    .btn { font-size: 0.875rem; padding: 0.5rem 0.75rem; border-radius: 6px; text-decoration: none; background: #f1f5f9; color: #475569; border: 1px solid #cbd5e1; font-weight: 500; }
    .btn:hover { background: #e2e8f0; }
    .btn-html { background: #2563eb; color: white; border-color: #1d4ed8; }
    .btn-html:hover { background: #1d4ed8; }
    footer { margin-top: 4rem; text-align: center; color: #64748b; font-size: 0.875rem; }
  </style>
</head>
<body>
  <h1>OrgScript Showcase</h1>
  <h2>Stable operational logic artifacts from source to visual documentation.</h2>
  
  <div class="grid">
    ${cards}
  </div>

  <footer>
    <hr>
    <p>Generated by OrgScript v${require("../package.json").version} &bull; <a href="https://github.com/DKFuH/OrgScript">GitHub</a></p>
  </footer>
</body>
</html>`;

  fs.writeFileSync(path.join(outputDir, "index.html"), indexHtml, "utf8");

  // Copy artifacts to site/artifacts
  const siteArtifactsDir = path.join(outputDir, "artifacts");
  fs.mkdirSync(siteArtifactsDir, { recursive: true });
  for (const base of examples.map(f => f.replace(".orgs", ""))) {
      const filesToCopy = [
          `${base}.formatted.orgs`,
          `${base}.summary.md`,
          `${base}.mermaid.md`,
      ];
      for (const f of filesToCopy) {
          const src = path.join(goldenDir, f);
          if (fs.existsSync(src)) {
              fs.copyFileSync(src, path.join(siteArtifactsDir, f));
          }
      }
  }

  // Copy demos to site/demos
  const siteDemosDir = path.join(outputDir, "demos");
  fs.mkdirSync(siteDemosDir, { recursive: true });
  const demoFiles = fs.readdirSync(htmlDemosDir).filter(f => f.endsWith(".html"));
  for (const file of demoFiles) {
    fs.copyFileSync(path.join(htmlDemosDir, file), path.join(siteDemosDir, file));
  }

  console.log(`Documentation site upgraded in ${outputDir}`);
}

main();
